version: "2"
services:
   db:
     image: postgres:9.5.4
     environment:
       POSTGRES_DB      : ontrack
       POSTGRES_USER    : ontrack
       POSTGRES_PASSWORD: ontrack
     ports:
       - "5432"
